### ISSUE TITLE
Check if the version is incremented, not just changed?

### ISSUE THREAD

**Issue by mcmire** [MetaMask/action-is-release#1]
For the `controllers` monorepo, we will be using `create-release-branch` and so release branches will no longer be created through a GitHub Action. That means we will need to remove the `if` check from the `is-release` job within `controllers`' `publish-release` workflow:

```
jobs:
  is-release:
    # release merge commits come from github-actions
    if: startsWith(github.event.commits[0].author.name, 'github-actions')
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/action-is-release@v1.0
        id: is-release
```

Removing this check means that the `is-release` job will run on all merges to main. Usually this won't be a problem, because this action (`is-release`) has a check of its own. However, all this action does is check that the root package version was bumped. That will happen, of course, when the version is incremented, but that will happen when it's decremented, too. I am not sure we want this. I think originally we just added a simple equality check because we wanted to allow for backport releases. However, even backport releases will increment the version. We will basically never have to decrement the version. The only case in which decrementing will occur is when the `publish-release` action doesn't work and we are forced to revert a release commit in order to redo it. As it stands, pushing such a commit would run `publish-release`, but shouldn't happen.
